name: TrueBan
version: ${project.version}
description: Trueban is a flexible ban management plugin for server owners who dont want to mess around with configuration files.
author: insanmiy
main: dev.insanmiy.trueban.TrueBan
api-version: 1.21

commands:
  ban:
    description: Ban a player
    usage: /ban <player> <reason>
    permission: trueban.ban
    aliases: []
  
  tempban:
    description: Temporarily ban a player
    usage: /tempban <player> <duration> <reason>
    permission: trueban.tempban
    aliases: []
  
  unban:
    description: Unban a player or IP
    usage: /unban <player|ip>
    permission: trueban.unban
    aliases: []
  
  ipban:
    description: Ban a player's IP address
    usage: /ipban <player|ip>
    permission: trueban.ipban
    aliases: []
  
  kick:
    description: Kick a player from the server
    usage: /kick <player> <reason>
    permission: trueban.kick
    aliases: []
  
  mute:
    description: Permanently mute a player
    usage: /mute <player> <reason>
    permission: trueban.mute
    aliases: []
  
  tempmute:
    description: Temporarily mute a player
    usage: /tempmute <player> <duration> <reason>
    permission: trueban.tempmute
    aliases: []
  
  unmute:
    description: Unmute a player
    usage: /unmute <player>
    permission: trueban.unmute
    aliases: []
  
  history:
    description: View punishment history for a player
    usage: /history <player>
    permission: trueban.history
    aliases: []

permissions:
  trueban.ban:
    description: Permission to ban players
    default: op
  
  trueban.tempban:
    description: Permission to temporarily ban players
    default: op
  
  trueban.unban:
    description: Permission to unban players
    default: op
  
  trueban.ipban:
    description: Permission to IP ban players
    default: op
  
  trueban.kick:
    description: Permission to kick players
    default: op
  
  trueban.mute:
    description: Permission to permanently mute players
    default: op
  
  trueban.tempmute:
    description: Permission to temporarily mute players
    default: op
  
  trueban.unmute:
    description: Permission to unmute players
    default: op
  
  trueban.history:
    description: Permission to view punishment history
    default: op
  
  trueban.bypass:
    description: Permission to bypass all punishments
    default: false
  
  trueban.notify:
    description: Permission to receive moderation notifications
    default: op
  
  trueban.mod:
    description: Permission for moderator commands
    default: op
  
  trueban.admin:
    description: Permission for admin commands
    default: op
  
  trueban.*:
    description: Permission for all TrueBan commands
    default: false
    children:
      trueban.ban: true
      trueban.tempban: true
      trueban.unban: true
      trueban.ipban: true
      trueban.kick: true
      trueban.mute: true
      trueban.tempmute: true
      trueban.unmute: true
      trueban.history: true
      trueban.notify: true
      trueban.mod: true
      trueban.admin: true
